#!/usr/bin/env python3
"""GLOSSARY - hand-written definitions for the vocabulary a 1668 Puritan text
leans on.  These win over WordNet and Webster's, because the machine-readable
sources give modern or wrong senses for exactly these words
(e.g. WordNet: "repentance - remorse for your past conduct").

Plain modern English, one to two sentences, written for a reader of Watson.
"""

GLOSSARY = {
    # --- the doctrine itself
    "repentance": "Sorrow for sin joined to a real turning from it: in Puritan use it has two parts, mortification (dying to sin) and vivification (living to righteousness).",
    "mortification": "Putting sin to death in the soul - not merely sorrowing over it, but weakening and killing its power by the Spirit.",
    "vivification": "The second half of repentance: the quickening of the soul to new life and obedience, as sin is put to death.",
    "humiliation": "Being brought low before God under a sense of sin; the soul's self-abasement, shame and submission.",
    "contrition": "Godly sorrow of heart for sin, arising from love to God rather than only fear of punishment.",
    "attrition": "Sorrow for sin that rises from fear of punishment rather than love of God - the counterfeit of true contrition.",
    "compunction": "A pricking or stinging of the conscience; sharp inward grief for sin.",
    "impenitent": "Continuing in sin without repentance; not sorry for sin, or not turning from it.",
    "obduracy": "Hardness of heart; an obstinate, unmeltable refusal to repent.",
    "hardness of heart": "A heart grown insensible to sin and to God's calls - the opposite of a heart of flesh.",
    "unregenerate": "Not yet born again; still in the natural state, untouched by saving grace.",
    "regeneration": "The new birth: God's work of giving spiritual life to a dead soul.",
    "conversion": "The soul's turning from sin to God; the first great work of grace in a sinner.",
    "effectual calling": "God's inward call by his Spirit, which does not merely offer grace but actually brings the sinner to Christ.",
    "backsliding": "Slipping back from a former profession or warmth toward God, often by degrees.",
    "apostasy": "A falling away: the deliberate abandonment of the faith once professed.",
    "presumption": "A groundless confidence in God's mercy without repentance; expecting pardon while cherishing sin.",
    "despair": "The opposite error: giving up hope of mercy, so that a soul refuses to come to God at all.",
    "hypocrisy": "Wearing the outward face of religion while the heart is unchanged; a counterfeit of grace.",
    "formalism": "Contentment with the outward form of religion - duties performed, the heart absent.",
    "pharisee": "In the Gospels, a member of a strict religious party; in Puritan usage, a self-righteous person who trusts in his own duties.",
    "publican": "A tax collector, despised in the Gospels; used as the pattern of a humble, self-accusing sinner whom God justifies.",
    "legalist": "One who seeks acceptance with God by keeping the law in his own strength, rather than by grace through Christ.",
    "antinomian": "One who turns grace into licence, claiming that since grace abounds the believer need not keep the law.",
    "merit": "That which earns a reward as a matter of debt. Puritan writers deny that any creature can merit of God in strict justice.",
    "supererogation": "The Roman Catholic notion of doing more than duty requires, and storing up the surplus as merit - denied by the Reformers.",

    # --- the machinery of salvation
    "grace": "God's free and undeserved favour, and the power that comes with it to change and keep the soul.",
    "mercy": "God's compassion toward the miserable and guilty, withholding the punishment they deserve.",
    "pardon": "Forgiveness of sin, freely granted by God for Christ's sake.",
    "remission": "The cancelling of sin's guilt and penalty; forgiveness described as a release from debt.",
    "justification": "God's act of declaring a believing sinner righteous, on the ground of Christ's righteousness, not his own.",
    "sanctification": "God's work of making the believer holy, begun here and completed in glory.",
    "adoption": "God's taking believers into his family as sons and daughters, with all the privileges of children.",
    "election": "God's eternal, gracious choice of some to salvation in Christ, not based on foreseen merit.",
    "reprobation": "The decree leaving others to the sin they love, justly punished; the dark side of the doctrine of election.",
    "perseverance": "The preserving of true believers by God's power so that they are not finally lost.",
    "atonement": "Christ's work of reconciling God and sinners by bearing sin's penalty in their place.",
    "propitiation": "The sacrifice that satisfies God's just wrath against sin, so that mercy can flow out freely.",
    "expiation": "The removing and covering of guilt by sacrifice.",
    "satisfaction": "In theology, Christ's payment answering fully the justice of God on behalf of his people.",
    "imputation": "Reckoning or crediting to another's account: Adam's sin to his posterity, and Christ's righteousness to believers.",
    "redemption": "Deliverance by the payment of a price - the purchase of sinners out of bondage to sin and Satan.",
    "mediator": "One who stands between God and man; Christ is the one mediator, both God and man.",
    "intercession": "Christ's pleading for his people at God's right hand; also a believer's prayers for others.",
    "covenant of works": "God's arrangement with Adam, promising life for perfect obedience - broken in the fall.",
    "covenant of grace": "God's gracious arrangement to save sinners through faith in Christ, and to make them like him.",
    "gospel": "The good news that God saves sinners through the life, death and resurrection of Jesus Christ.",

    # --- sin and its colours
    "sin": "Any want of conformity to, or transgression of, the law of God - in heart, word or deed.",
    "iniquity": "Sin as crookedness or moral distortion; the guilt and perversity of wrongdoing.",
    "transgression": "The crossing of a boundary - the law of God broken by a deliberate act.",
    "trespass": "A wandering over the line; an offence against God's law and honour.",
    "concupiscence": "Inward craving or desire, especially disordered sexual desire; in Puritan use, the root of actual sins.",
    "lust": "Any strong inordinate desire, not only sexual; the heart's craving for what God forbids.",
    "corruption": "Sin as it works in the soul's faculties: the souring of a nature made upright.",
    "flesh": "In Paul, human nature as it is apart from grace, hostile to God - not the body as such.",
    "world": "In Paul and John, the whole system of life that leaves God out and opposes him.",
    "covetousness": "Greed for what is not ours, especially money; in the New Testament, 'idolatry'.",
    "vainglory": "Boasting vanity; the craving for praise and appearance rather than substance.",
    "malice": "Deliberate ill will toward another; the desire to harm.",
    "uncleanness": "Impurity, especially sexual sin; in scripture, whatever defiles the soul before God.",
    "guilt": "The state of deserving punishment for sin, and the conscience's sense of that desert.",
    "inherent": "Present within and belonging to the thing itself; sin is inherent in the natural man.",
    "worldliness": "Being shaped by and given to the present age rather than to God.",

    # --- sin's craftsman
    "satan": "The great adversary of God and his people; the accuser, tempter and deceiver.",
    "devil": "The ruler of darkness, whose name means slanderer or accuser; the devil with his devices.",
    "devices": "Brooks's word for Satan's stratagems, schemes and contrivances against the soul - underhanded plots, not open force.",
    "wiles": "Crafty tricks or deceits; the subtle methods by which a soul is drawn into sin.",
    "temptation": "Both the solicitation to sin and the trial by which faith is tested; the same word carries both senses.",
    "fiery darts": "Paul's picture (Eph. 6:16) of Satan's sudden, burning suggestions - terrified suggestions of conscience, or inflamings of lust, to be quenched by faith.",
    "accuser": "Satan's role in accusing the believer before God and in the conscience.",

    # --- means and duties
    "means of grace": "The appointed ways God gives grace and keeps it: the word, prayer, sacraments, and the fellowship of the church.",
    "ordinance": "Anything God has appointed by which he gives grace - preaching, the sacraments, prayer, meditation.",
    "sacrament": "A visible sign and seal given by Christ: baptism and the Lord's Supper.",
    "sabbath": "The day set apart for God's worship and rest; the Puritan 'market day of the soul'.",
    "affliction": "Trouble sent by a wise Father as a medicine, to humble, purge and advance the soul.",
    "chastisement": "Corrective discipline from a loving God, aimed at the repentance and good of his child.",
    "rod": "In scripture, the instrument of discipline; the stroke by which the loving Father corrects his children.",
    "conscience": "God's deputy in the soul, accusing or excusing; a tender conscience is a great mercy.",
    "meditation": "Deliberate, extended thinking upon divine things - in Puritan practice, a duty, not a reverie.",
    "self-examination": "The disciplined inner trial of one's own state and ways, to prove whether grace is real - the instrument of the believer's comfort or of the sinner's awakening.",
    "providence": "God's wise and holy ordering of all things to his glory and his people's good.",
    "mercy-seat": "The place of propitiation; in Christ, the meeting point of justice and mercy.",
    "wrath": "God's just anger against sin; in the New Testament, not a rage to be feared as a temper but a settled, holy opposition to evil.",

    # --- fruit, false and true
    "sincerity": "Singleness of heart - being what one appears to be before God, without mixture.",
    "zeal": "Hot and earnest love working outward in labour for God's glory.",
    "watchfulness": "The habitual guard the believer keeps over heart, words and ways.",
    "tenderness of heart": "A soft, easily touched conscience that bleeds at the smallest sin.",
    "broken heart": "The heart crushed with grief for sin - a sacrifice God never refuses.",
    "mourning": "Godly grief for sin; one of the ways the Spirit shows repentance is real.",
    "prayer": "The soul's speaking to God; in Puritan writing it is the pulse of spiritual life.",
    "fasting": "Abstaining for a season to seek God, especially in seasons of humiliation.",
    "humility": "Low thoughts of oneself and high thoughts of God; the root of all real obedience.",
    "patience": "Bearing affliction without fury or fainting, trusting God's timing and wisdom.",
    "temperance": "Moderation and self-command in things lawful, so they do not become masters.",

    # --- last things
    "damnation": "Final condemnation, the just sentence of sin in eternity.",
    "eternal life": "The life of glory with God, begun now in grace and never ending.",
    "judgment": "The day when God will judge all by Jesus Christ; also his present judgments in history.",
    "reprobate": "Cast away or rejected after testing - one given over to a useless mind.",

    # --- archaic words and forms a modern reader trips over
    "besom": "A broom made of twigs; used in scripture (Isa. 14:23) for a sweeping instrument of destruction.",
    "froward": "Perverse and disobedient; turned away from what is right; stubbornly contrary.",
    "shew": "An older spelling of 'show'.",
    "doth": "Older form of 'does'.",
    "hath": "Older form of 'has'.",
    "saith": "Older form of 'says'.",
    "dost": "Older form of 'do' (with thou): 'thou dost'.",
    "hast": "Older form of 'have' (with thou): 'thou hast'.",
    "wilt": "Older form of 'will' (with thou): 'thou wilt'.",
    "shalt": "Older form of 'shall' (with thou): 'thou shalt'.",
    "art": "Older form of 'are' (with thou): 'thou art'.",
    "ye": "An older form of 'you', used as a plural or formal form.",
    "thou": "An older form of 'you', singular and familiar; in prayer it was used to address God intimately.",
    "thee": "The object form of 'thou': 'to thee'.",
    "thy": "An older possessive form: 'thy God'.",
    "thine": "An older possessive form, used before a vowel: 'thine eyes'.",
    "hitherto": "Up to this time; until now.",
    "thence": "From that place; from there.",
    "hence": "From this place, time or cause; therefore.",
    "verily": "Truly; certainly. 'Verily, verily' in John is a double affirmation.",
    "yea": "Yes; indeed - not merely an affirmative but a stronger one: 'yea, more than that'.",
    "nay": "No; indeed not.",
    "alas": "An exclamation of grief or pity: 'alas, poor soul!'",
    "woe": "An exclamation of grief or threatened judgment; a cry of sorrow over a person's doom.",
    "sundry": "Various, several, of different kinds.",
    "meet": "Fitting, suitable or proper for the purpose - as in 'meet for the kingdom'.",
    "fain": "Gladly, willingly - 'I would fain do it'.",
    "nought": "Nothing.",
    "aught": "Anything.",
    "chasten": "To discipline or correct, as a loving father corrects a child.",
    "cleave": "To hold fast to; to cling - 'cleave to the Lord'.",
    "wax": "To grow or become gradually - 'wax worse and worse'.",
    "quick": "Living, alive - 'the quick and the dead'.",
    "record": "In scripture, a witness borne; 'God is my record' means 'God is my witness'.",
    "peculiar": "Belonging exclusively to someone; God's 'peculiar people' are his own possession.",
    "conversation": "In older English, one's whole manner of life and conduct, not only speech.",
    "prevent": "In older English, to go before or forestall - not to stop. God's mercy 'prevented' the Psalmist means it went before him.",
    "let": "In older English, to hinder or obstruct (as in 'let or hindrance').",
    "suffer": "In older English, to allow or permit - 'suffer me to speak'.",
    "admire": "In older English, to wonder at; to be astonished by.",
    "deceive": "To mislead by a lie; in scripture the great work of Satan on the understanding.",
    "sore": "Severely, grievously - 'struck sore'.",
    "anon": "Soon; in a little while.",
    "wont": "Accustomed to; used to do something.",
    "haply": "Perhaps, by chance.",
    "peradventure": "Perhaps, by chance - 'if peradventure they will hear'.",

    # --- forms Watson actually uses (added after checking the book's vocabulary)
    "repent": "To be sorry for sin and to turn from it; in Watson's usage it always means both, not merely regret.",
    "repenting": "The ongoing act of turning from sin to God - repentance as a life, not a single event.",
    "mortify": "To put sin to death; to weaken and destroy its power in the soul by the Spirit.",
    "mortifying": "Putting sin to death - the daily work of the believer, especially in its first great stroke at conversion.",
    "sorrow": "Grief; in 'godly sorrow' it is grief for sin because it offends a good God, not merely because it brings trouble.",
    "conviction": "Being convinced of sin by the Spirit - the awakening that goes before repentance; conviction may exist without conversion.",
    "hypocrite": "One who acts a part: a professor of religion whose heart is not changed.",
    "sinner": "One who has broken God's law - in scripture, every human being; the word of grace is that Christ came to save such.",
    "wicked": "Morally evil before God; those who live as if God were not there.",
    "saint": "In scripture, any person made holy by God's grace - not a spiritual elite.",
    "ordinances": "The things God has appointed for worship and for giving grace: preaching, the sacraments, prayer.",
    "gospel": "The good news that God saves sinners through the life, death and resurrection of Jesus Christ.",
    "christ": "The anointed one - the Messiah; the God-man who saves his people from their sins.",
    "conscience": "God's deputy in the soul, accusing or excusing; a tender conscience is a great mercy.",
    "preach": "To declare God's word; in Puritan confidence, the ordinary means by which faith is given.",
    "justify": "To declare righteous; God justifies the sinner who believes, on the ground of Christ's righteousness.",
    "sanctify": "To set apart as holy and to make holy by degrees - the Spirit's ongoing work in the believer.",
    "repentance unto life": "Repentance that is the gift of God and leads to salvation - distinguished from mere sorrow or a deathbed fright.",

    # --- forms Watson actually uses (added after checking the book's vocabulary)
    "repent": "To be sorry for sin and to turn from it; in Watson's usage it always means both, not merely regret.",
    "repenting": "The ongoing act of turning from sin to God - repentance as a life, not a single event.",
    "mortify": "To put sin to death; to weaken and destroy its power in the soul by the Spirit.",
    "mortifying": "Putting sin to death - the daily work of the believer, especially in its first great stroke at conversion.",
    "sorrow": "Grief; in 'godly sorrow' it is grief for sin because it offends a good God, not merely because it brings trouble.",
    "conviction": "Being convinced of sin by the Spirit - the awakening that goes before repentance; conviction may exist without conversion.",
    "hypocrite": "One who acts a part: a professor of religion whose heart is not changed.",
    "sinner": "One who has broken God's law - in scripture, every human being; the word of grace is that Christ came to save such.",
    "wicked": "Morally evil before God; those who live as if God were not there.",
    "saint": "In scripture, any person made holy by God's grace - not a spiritual elite.",
    "ordinances": "The things God has appointed for worship and for giving grace: preaching, the sacraments, prayer.",
    "gospel": "The good news that God saves sinners through the life, death and resurrection of Jesus Christ.",
    "christ": "The anointed one - the Messiah; the God-man who saves his people from their sins.",
    "conscience": "God's deputy in the soul, accusing or excusing; a tender conscience is a great mercy.",
    "preach": "To declare God's word; in Puritan confidence, the ordinary means by which faith is given.",
    "justify": "To declare righteous; God justifies the sinner who believes, on the ground of Christ's righteousness.",
    "sanctify": "To set apart as holy and to make holy by degrees - the Spirit's ongoing work in the believer.",
    "repentance unto life": "Repentance that is the gift of God and leads to salvation - distinguished from mere sorrow or a deathbed fright.",
}
